"use client";
import "./globals.css";
import { memo } from "react";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { MantineProvider } from "@mantine/core";
import 'leaflet/dist/leaflet.css'; 
import 'leaflet-draw/dist/leaflet.draw.css';
// import { NotificationsProvider } from "@mantine/notifications";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Revetment",
//   description: "Generated by  Revetment.com",
// };
const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <MantineProvider withGlobalStyles withNormalizeCSS>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
};
export default memo(RootLayout);
